import 'package:bob_hacks/constants/image_constants.dart';
import 'package:flutter/material.dart';

import 'chapter.dart'; // Ensure this path is correct

class Modules {
  final String title;
  final String description;
  final String module;
  final String translate;
  final String chapters;
  final List<Chapter> chaptersList;

  Modules({
    required this.title,
    required this.description,
    required this.module,
    required this.translate,
    required this.chapters,
    required this.chaptersList,
  });

  static final List<Modules> modules = [
    Modules(
      chapters: "5 chapters",
      title: "Introduction to Stock Market",
      description:
          "The stock market can play a pivotal role in ensuring your financial security. In this module, you will learn how to get started in the stock market, its fundamentals, how it functions, and the various intermediaries that appertain it.",
      module: "View Module",
      translate: "Translate हिंदी",
      chaptersList: [
        Chapter(
          number: 1,
          title: "The Need to Invest",
          description:
              "Learn about the importance of savings and identify avenues to invest the savings in a suitable investment vehicle. Compare historical returns generated by different assets, and know what to expect from you.",
          imgpath:AssetsConstant.ch1,
        ),
        Chapter(
            number: 2,
            title: "Regulators, the guardians of capital markets",
            description:
                "Find out who and how the regulators govern the financial markets and understand different types of financial market participants. Understand the need to regulate the markets.",
            imgpath: AssetsConstant.ch2),
        Chapter(
            number: 3,
            title: "Market Intermediaries",
            description:
                "An overview of the financial intermediaries in the stock market and the services they offer.",
            imgpath: AssetsConstant.ch3),
        Chapter(
            number: 4,
            title: "How the Stock Market Works",
            description:
                "Learn how the stock market functions, including the trading mechanisms, order types, and the role of exchanges.",
            imgpath:AssetsConstant.ch4),
        Chapter(
            number: 5,
            title: "Getting Started with Investing",
            description:
                "Understand the steps to start investing in the stock market, including opening a brokerage account and selecting investments.",
            imgpath: AssetsConstant.ch5),
      ],
    ),
    Modules(
      chapters: "4 chapters",
      title: "Technical Analysis",
      description:
          "Technical Analysis (TA) helps in developing a point of view. In this module, we will discover the complex attributes, various patterns, indicators, and theories of TA that will help you as a trader to find upright trading opportunities in the market.",
      module: "View Module",
      translate: "Translate हिंदी",
      chaptersList: [
        Chapter(
            number: 1,
            title: "Introduction to Technical Analysis",
            description:
                "Understand the basics of technical analysis and how it differs from fundamental analysis.",
            imgpath: AssetsConstant.ch3),
        Chapter(
            number: 2,
            title: "Chart Patterns",
            description:
                "Learn about various chart patterns, including head and shoulders, double tops and bottoms, and flags and pennants.",
            imgpath:AssetsConstant.ch2),
        Chapter(
            number: 3,
            title: "Technical Indicators",
            description:
                "Discover the most commonly used technical indicators, such as moving averages, RSI, MACD, and Bollinger Bands.",
            imgpath: AssetsConstant.ch4),
        Chapter(
            number: 4,
            title: "Applying Technical Analysis",
            description:
                "Learn how to apply technical analysis to real-world trading scenarios and develop your trading strategy.",
            imgpath: AssetsConstant.ch1),
      ],
    ),
    Modules(
      chapters: "3 chapters",
      title: "Fundamental Analysis",
      description:
          "The Fundamental Analysis (FA) module explores equity research by reading financial statements and annual reports, calculating and analyzing financial ratios, and evaluating the intrinsic value of a stock to find long-term investing opportunities.",
      module: "View Module",
      translate: "Translate हिंदी",
      chaptersList: [
        Chapter(
            number: 1,
            title: "Introduction to Fundamental Analysis",
            description:
                "Learn the basics of fundamental analysis and why it is important for long-term investing.",
            imgpath: AssetsConstant.ch5),
        Chapter(
            number: 2,
            title: "Financial Statements",
            description:
                "Understand how to read and analyze financial statements, including the income statement, balance sheet, and cash flow statement.",
            imgpath: AssetsConstant.ch3),
        Chapter(
            number: 3,
            title: "Financial Ratios and Valuation",
            description:
                "Learn how to calculate and use key financial ratios to evaluate a company's performance and determine its intrinsic value.",
            imgpath:AssetsConstant.ch1),
      ],
    ),
    Modules(
      chapters: "6 chapters",
      title: "Futures Trading",
      description:
          "Futures Trading is a segment of the derivatives market. This module covers the various intricacies involved in undergoing a futures trade, including margins, leverages, pricing, etc. It also discusses the use of derivatives for hedging purposes.",
      module: "View Module",
      translate: "Translate हिंदी",
      chaptersList: [
        Chapter(
            number: 1,
            title: "Introduction to Futures Trading",
            description:
                "Learn the basics of futures trading and the different types of futures contracts.",
            imgpath: AssetsConstant.ch3),
        Chapter(
            number: 2,
            title: "Understanding Margins and Leverages",
            description:
                "Understand the concepts of margins and leverages and how they apply to futures trading.",
            imgpath: AssetsConstant.ch4),
        Chapter(
            number: 3,
            title: "Futures Pricing",
            description:
                "Learn how futures contracts are priced and the factors that influence their prices.",
            imgpath: AssetsConstant.ch5),
        Chapter(
            number: 4,
            title: "Hedging with Futures",
            description:
                "Discover how futures can be used for hedging purposes to manage risk.",
            imgpath: AssetsConstant.ch4),
        Chapter(
            number: 5,
            title: "Trading Strategies",
            description:
                "Learn about different futures trading strategies and how to apply them.",
            imgpath: AssetsConstant.ch3),
        Chapter(
            number: 6,
            title: "Regulations and Market Participants",
            description:
                "Understand the regulatory environment for futures trading and the key market participants.",
            imgpath: AssetsConstant.ch1),
      ],
    ),
    Modules(
      chapters: "4 chapters",
      title: "Options Theory for Professional Trading",
      description:
          "Options Trading is a segment of the derivatives segment. Options contracts grant the buyer the right to buy/sell the underlying without a compulsory obligation. This module discusses options contracts, pricing, and their profit and loss payoffs.",
      module: "View Module",
      translate: "Translate हिंदी",
      chaptersList: [
        Chapter(
          number: 1,
          title: "Introduction to Options Trading",
          description:
              "Learn the basics of options trading and the different types of options contracts.",
          imgpath: AssetsConstant.ch1,
        ),
        Chapter(
            number: 2,
            title: "Options Pricing",
            description:
                "Understand how options are priced and the factors that influence their prices.",
            imgpath:AssetsConstant.ch2),
        Chapter(
            number: 3,
            title: "Profit and Loss Payoffs",
            description:
                "Learn how to calculate profit and loss payoffs for different options strategies.",
            imgpath:AssetsConstant.ch3),
        Chapter(
            number: 4,
            title: "Advanced Options Strategies",
            description:
                "Discover advanced options trading strategies and how to apply them.",
            imgpath: AssetsConstant.ch5),
      ],
    ),
  ];
}
