// export const metadata = {
//   title: "Lawyantra",
//   description: "Generated by create next app",
// };

const Layout = ({ children }) => (
  <div>
    <div className="bg-[#F5D0D8] w-[100%] h-[100px] flex flex-row justify-evenly items-center">
      <div className="flex flex-row items-end relative w-[300px]">
        <img className="h-[90px] m-2" src={`/images/image1.png`} />
        <img
          className="m-2  absolute bottom-[-45px] left-[60px]"
          src={`/images/image2.png`}
        />
      </div>
      <div className=" flex flex-col justify-center">
        <p className="text-[#6A4FF7] text-[28px] font-medium leading-8">
          Let’s analyse your expenses
        </p>
      </div>

      <div className="flex flex-row items-end relative w-[300px]">
        <img className="h-[100px] m-2" src={`/images/image3.png`} />
        <img
          className="m-2 absolute bottom-[-10px] left-[60px]"
          src={`/images/image4.png`}
        />
      </div>
    </div>
    <main className="flex flex-col flex-grow relative">{children}</main>
  </div>
);

export default Layout;
